app/__init__.py
# app/__init__.py
import logging
from flask import Flask
from flask import has_request_context, request
from flask.logging import default_handler

class RequestFormatter(logging.Formatter):
    def format(self, record):
        if has_request_context():
            record.url = request.url
            record.remote_addr = request.remote_addr
        else:
            record.url = None
            record.remote_addr = None

        return super().format(record)


# mail_handler.setFormatter(formatter)


def create_app():
    app = Flask(__name__)
    app.static_folder = 'static'
    loggy = logging.getLogger(__name__)
    loggy.addHandler(default_handler)
    loggy.setLevel(logging.DEBUG)

    formatter = RequestFormatter(
    '[%(asctime)s] %(remote_addr)s requested %(url)s\n'
    '%(levelname)s in %(module)s: %(message)s'
    )
    default_handler.setFormatter(formatter)

    # Register blueprints
    from app.views.main import main_bp
    from app.views.main import api_bp

    app.register_blueprint(main_bp, url_prefix='/')
    app.register_blueprint(api_bp, url_prefix='/api')

    return app, loggy

app/views/main.py
from flask import render_template, request, jsonify, Blueprint, current_app
from app.auth.login import login as key
import logging

################ VIEWS BLUEPRINT ################
main_bp = Blueprint('main', __name__)
api_bp = Blueprint('api', __name__)

@main_bp.route('/')
def index():
    return render_template('index.html', title='Home')

@main_bp.route('/about')
def about():
    return render_template('about.html', title='About Us')

@main_bp.route('/login')
def auth():
    return render_template('login.html', title='Login')
# Add more routes as needed

############## API BLUEPRINT ################
@api_bp.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    print(data)
    if data is not None:
        # Fetch the login key
        res = key(data['usrn'], data['pdrd'])

        # Process the JSON data
        result = {'message': f"{res}"}
        return jsonify(result), 200

    else:
        error_message = {'error': 'Invalid JSON data'}
        return jsonify(error_message), 400

    

app/templates/about.html
<!-- templates/about.html -->
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
    <h1>About Us</h1>
    <p>This is the about us page content.</p>
    <a href="{{ url_for('main.index') }}">Go back to Home</a>
{% endblock %}

app/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
    <title>{% block title %}My Flask App{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/index.html
<!-- templates/index.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Welcome to our Home Page</h1>
    <p>This is the home page content.</p>
    <a href="{{ url_for('main.about') }}">Learn more about us</a>
{% endblock %}

app/templates/login.html
<!-- templates/login.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form id="login-form">
        <input id="login-username" type="text" />
        <input id="login-password" type="password" />
        <button type="submit">Submit</button>
    </form>
    
{% endblock %}